SebaS
DiegoFelipeOrozco/pet-book pull request #2
Opened 2020-09-16 00:20 UTC by sebas551v

Test image-gallery

2020-09-16 17:22 UTC, DiegoFelipeOrozco requested changes

2020-09-16 17:22 UTC, DiegoFelipeOrozco commented on src/app/image-gallery/image-gallery.component.spec.ts
> +    it("Verifica el valor de la propiedad 'deshabilitado' de los botones", () => {
no respeta el patron Gerkin

2020-09-16 17:22 UTC, DiegoFelipeOrozco commented on src/app/image-gallery/image-gallery.component.spec.ts
> +    it('Cuando se carga la vista, debe exisitr un contenedor de imágen con la clase .img', () => {
¿no es un lenguaje demasiado técnico para entenderlo una entidad de negocio?

- [ ] revisar que respete los estándares y principios enseñados en clase

2020-09-16 17:22 UTC, DiegoFelipeOrozco commented on src/app/app.component.spec.ts
> +xdescribe('AppComponent', () => {
no debería haber pruebas des-habilitadas, da la noción de que están a medio hacer

2020-09-24 10:27 UTC, sebas551v commented on src/app/image-description/image-description.component.ts
> +}
Listo!

2020-09-24 10:27 UTC, sebas551v commented on src/app/image-description/image-description.component.spec.ts
> +});
El mismo anterior

2020-09-24 10:29 UTC, sebas551v commented on src/app/image-gallery/image-gallery.component.spec.ts
> +    it("Verifica el valor de la propiedad 'deshabilitado' de los botones", () => {
Qué cosa no lo respeta? Dado que hay un botón, cuando esté deshabilitado entonces muestre la alerta ¿?

2020-09-24 10:30 UTC, sebas551v commented on src/app/image-gallery/image-gallery.component.spec.ts
> +    it('Cuando se carga la vista, debe exisitr un contenedor de imágen con la clase .img', () => {
En clase vimos que debe ser descriptivo, qué más descriptivo que especificar la clase.

2020-09-24 10:31 UTC, sebas551v commented on src/app/app.component.spec.ts
> +xdescribe('AppComponent', () => {
Eso no lo toqué, debe estar desde que lo hicimos en clase. Ya está habilitada

2020-09-24 18:29 UTC, DiegoFelipeOrozco commented on src/app/image-gallery/image-gallery.component.spec.ts
> +    it("Verifica el valor de la propiedad 'deshabilitado' de los botones", () => {
GIVEN...WHEN...THEN el profe en los ejemplos que hizo no pone el GIVEN pero si los otros dos, en el reporte del navegador debería poderlo leer alguien que no es programador y saber que es lo que funciona y que no

2020-09-24 19:42 UTC, DiegoFelipeOrozco requested changes
todavía faltan conversaciones por resolver

2020-09-24 20:16 UTC, DiegoFelipeOrozco requested changes

2020-09-24 20:16 UTC, DiegoFelipeOrozco commented on src/app/image-gallery/image-gallery.component.spec.ts
> +      expect(resp).toBeUndefined;
```suggestion
      expect(resp).toBeUndefined();
```

2020-09-24 20:24 UTC, DiegoFelipeOrozco approved these changes
![image](https://user-images.githubusercontent.com/25964323/94196478-07e2f100-fe7a-11ea-8848-10fb21046ca7.png)

2020-09-24 20:25 UTC, merged