tests unit image-details, image-gallery
DiegoFelipeOrozco/pet-book pull request #4
Opened 2020-09-24 22:24 UTC by KatherinePosada

Cambios en las pruebas unitarias después de borrar rama anterior y crear rama nueva Katherine.

2020-09-24 22:53 UTC, DiegoFelipeOrozco requested changes

2020-09-24 22:53 UTC, DiegoFelipeOrozco commented on src/app/image-details/image-details.component.spec.ts
> +  });
esta prueba unitaria ya se hizo...y pertenece a ImageService, ademas: si lo esperado es que falle entonces programa eso en el expect, por ejemplo `expect(response).not().toEqual(imageResponse);`
```suggestion
```

2020-09-24 22:53 UTC, DiegoFelipeOrozco commented on src/app/image-gallery/image-gallery.component.html
> +            <img src="{{img.url}}" id="img{{img.id}}" class="img" width="240" height="170">
se supone que estamos haciendo las pruebas unitarias, no desarrollando la aplicación, no entiendo el propósito de estos cambios

- [ ] adjuntar informe en el que se evidencie que las pruebas ya programadas no saltaron

2020-09-24 23:02 UTC, KatherinePosada commented on src/app/image-gallery/image-gallery.component.html
> +            <img src="{{img.url}}" id="img{{img.id}}" class="img" width="240" height="170">
pero necesitaba identificar cada id para desarrollar la prueba, sí se pueden hacer cambios en el código de la app para hacer esto.
Adjunto evidencia de que solo las dos pruebas que tengo fallando a proposito lo hicieron
![image](https://user-images.githubusercontent.com/14101787/94208677-0290a100-fe90-11ea-825f-b451949c290a.png)

2020-09-24 23:07 UTC, KatherinePosada commented on src/app/image-details/image-details.component.spec.ts
> +  });
Cambios realizados.
![image](https://user-images.githubusercontent.com/14101787/94208992-c9a4fc00-fe90-11ea-8a7e-484313842108.png)

2020-09-25 01:47 UTC, DiegoFelipeOrozco approved these changes
se aprueban porque no hay errores críticos, pero se recomienda considerar mas los principios FIRST y manejar en la descripción de los test GIVEN WHEN THEN y que algunos test están duplicados en esencia

2020-09-25 01:49 UTC, merged